server:
  port: 8080

spring:
  application:
    name: auth-service

  flyway:
    enabled: true
    locations: classpath:db/migration

management:

  endpoints:

    web:

      exposure:

        include: health,info,prometheus

  endpoint:

    health:

      show-details: always

      probes:
        enabled: true

  health:

    livenessstate:
      enabled: true

    readinessstate:
      enabled: true

  prometheus:

    metrics:

      export:

        enabled: true

  metrics:

    tags:

      application: ${spring.application.name}